apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
    replicas: 1
    selector:
        matchLabels:
          app: app1
    template:
        metadata:
          labels:
              app: app1
        spec:
          containers:
          - name: app1
            image: shitomo/app1:latest
            ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
    selector:
      app: app1
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
    replicas: 1
    selector:
        matchLabels:
          app: app2
    template:
        metadata:
          labels:
              app: app2
        spec:
          containers:
          - name: app2
            image: shitomo/app2:latest
            ports:
            - containerPort: 8080
            env:
            - name: API_SERVER_URL
              value: http://app1:80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080